# Generated by Django 5.1.1 on 2024-09-28 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_duration_set_remove_projectassignment_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='duration',
            old_name='Projects',
            new_name='projects',
        ),
        migrations.RenameField(
            model_name='duration',
            old_name='Value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='Managers',
            new_name='managers',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='Skills',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='Teamleads',
            new_name='teamleads',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='Timeperiod',
            new_name='timeperiod',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Skills',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Teamleads',
            new_name='teamleads',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='Value',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='project',
            name='duration',
        ),
        migrations.AddField(
            model_name='duration',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='dashboard.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='dashboard.project'),
        ),
        migrations.AddField(
            model_name='skill',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='dashboard.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='finish_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
