# Generated by Django 5.1.1 on 2024-09-29 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_projects_duration_projects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skills',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='value',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_lead', models.CharField(max_length=255, null=True)),
                ('date', models.DateField(null=True)),
                ('value', models.IntegerField(default=0)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamleads', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='DS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ds', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='FS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fs', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='MGskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, null=True)),
                ('managers', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mgskills', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='PreferenceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_from', models.CharField(max_length=255, null=True)),
                ('project_to', models.CharField(max_length=255, null=True)),
                ('cost_value', models.IntegerField(default=0)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preference_costs', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Reqskill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, null=True)),
                ('projects', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reqskills', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamleads', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='dashboard.project')),
            ],
        ),
        migrations.CreateModel(
            name='WAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamleads', models.CharField(max_length=100, null=True)),
                ('value', models.IntegerField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wad', to='dashboard.project')),
            ],
        ),
    ]
