# Generated by Django 5.1.1 on 2024-10-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_projectfiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
