# Generated by Django 5.1.1 on 2024-10-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_score_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='file_type',
            field=models.CharField(blank=True, choices=[('plot', 'Plot File'), ('excel', 'Excel File')], max_length=10, null=True),
        ),
    ]
